/****************************************************************************
 * boards/arm/stm32n6/stm32n647-evb/scripts/ld.script
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ****************************************************************************/

#include <nuttx/config.h>

OUTPUT_ARCH(arm)
ENTRY(__start)

MEMORY
{
  flash (rx)  : ORIGIN = CONFIG_FLASH_START, LENGTH = CONFIG_FLASH_SIZE
  sram  (rwx) : ORIGIN = CONFIG_RAM_START,   LENGTH = CONFIG_RAM_SIZE
}

SECTIONS
{
  .text :
  {
    _stext = .;
    KEEP(*(.vectors))
    *(.text.startup)
    *(.text .text.*)
    *(.rodata .rodata.*)
    _etext = .;
  } > flash

  .init_section :
  {
    _sinit = .;
    *(.init_array .init_array.*)
    _einit = .;
  } > flash

  .data :
  {
    _sdata = .;
    *(.data .data.*)
    _edata = .;
  } > sram AT > flash

  .bss :
  {
    _sbss = .;
    *(.bss .bss.*)
    *(COMMON)
    _ebss = .;

    /* Define the idle stack at the top of SRAM */

    . = ALIGN(32);
    g_idle_topstack = .;
  } > sram
}
